#!/usr/bin/env bash
# Package construction shared by the publisher and its package cache.

locate_pixi_binary() {
	local extract_dir=$1

	if [[ -f $extract_dir/pixi ]]; then
		printf '%s\n' "$extract_dir/pixi"
		return
	fi

	local binary_path
	binary_path="$(find "$extract_dir" -type f -name 'pixi' | head -n 1)"
	[[ -n $binary_path ]] || fail "unable to locate pixi binary in extracted asset"
	printf '%s\n' "$binary_path"
}

write_control_file() {
	local control_file=$1
	local version=$2
	local arch=$3

	cat >"$control_file" <<EOF
Package: $PACKAGE_NAME
Version: $version
Section: utils
Priority: optional
Architecture: $arch
Maintainer: $DEB_MAINTAINER
Homepage: https://github.com/prefix-dev/pixi
Description: Cross-platform package manager and workflow tool
 Repackaged upstream Pixi Linux release binary from prefix-dev/pixi.
 This package is generated by an unofficial APT repository.
EOF
}

build_deb_from_asset() {
	local asset_path=$1
	local version=$2
	local arch=$3
	local release_id=$4
	local out_deb=$5

	local staging_dir="$WORK_DIR/package-build/$release_id/$arch"
	local extract_dir="$staging_dir/extract"
	local package_root="$staging_dir/root"
	rm -rf "$staging_dir"
	mkdir -p "$extract_dir" "$package_root/DEBIAN" "$package_root/usr/bin"
	chmod 0755 "$package_root" "$package_root/DEBIAN" "$package_root/usr" "$package_root/usr/bin"

	tar -xzf "$asset_path" -C "$extract_dir"
	local pixi_binary
	pixi_binary="$(locate_pixi_binary "$extract_dir")"
	install -m 0755 "$pixi_binary" "$package_root/usr/bin/pixi"
	write_control_file "$package_root/DEBIAN/control" "$version" "$arch"

	dpkg-deb --build --root-owner-group "$package_root" "$out_deb" >/dev/null
}
